services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: umu
      POSTGRES_PASSWORD: umu_password_change_me
      POSTGRES_DB: umuapp
    ports:
      - "5432:5432"
    volumes:
      - umuapp_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    environment:
      SECRET_KEY: change-me-in-prod
      DATABASE_URL: postgresql+psycopg://umu:umu_password_change_me@db:5432/umuapp
      ALLOWED_EMAIL_DOMAINS: umu.ac.ug,stud.umu.ac.ug
      REQUIRE_EMAIL_VERIFICATION: "false"
      CORS_ORIGINS: http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  umuapp_pgdata:

